# NumPy — Day 1

My first hands-on NumPy session, as part of my AI/ML journey. Everything in this notebook is something I actually typed and ran today: creating arrays, checking `.size` and `.shape`, and experimenting with `dtype` — including the errors I ran into.

This is Day 1 / basics only.

## 1. Installing NumPy

`pip` installs Python packages. NumPy was already installed in my Miniconda environment, so this only confirms it.

In [ ]:
!pip install numpy

**Result (in my Miniconda environment):** pip reports that the requirement is already satisfied.

## 2. Importing NumPy

NumPy is conventionally imported with the alias `np`.

In [2]:
import numpy as np

## 3. Creating a 1D array

`np.array()` builds a NumPy array from a Python sequence (here, a list). A flat list gives a **one-dimensional** array.

In [3]:
a1D = np.array([1, 2, 3, 4])
print(a1D)

[1 2 3 4]

**Result:** `[1 2 3 4]` — printed without commas, unlike a Python list.

## 4. Reading the documentation with `help()`

Instead of memorizing every parameter, `help()` shows a function's documentation, parameters, and options.

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, ndmax=0, like=None)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or i

**Takeaway:** `np.array` takes more than just the data — `dtype` (used heavily below) is one of its parameters.

## 5. Array size

`.size` is the **total number of elements** in the array.

In [5]:
a1D.size

4

**Result:** `4`

## 6. Multidimensional arrays

Nesting lists adds dimensions. This one has three levels of brackets, so it is a **3D** array.

In [6]:
arr = np.array([
    [
        [1, 2, 7],
        [4, 7, 5]
    ],
    [
        [7, 7, 8],
        [1, 2, 3]
    ]
])

print(arr)

[[[1 2 7]
  [4 7 5]]

 [[7 7 8]
  [1 2 3]]]


### Size and shape

In [7]:
arr.size

12

In [8]:
arr.shape

(2, 2, 3)

**Result:** `.size` is `12` and `.shape` is `(2, 2, 3)`.

Reading `(2, 2, 3)`:
- **2** blocks/groups
- each block has **2** rows
- each row has **3** elements

Total elements: 2 × 2 × 3 = **12**, which matches `.size`.

## 7. NumPy data types (`dtype`)

Every NumPy array has a `dtype` that decides what type of data it stores. NumPy offers fixed-size numeric types such as `np.int16` and `np.int32`.

In [9]:
np.int16

numpy.int16

In [10]:
np.int32

numpy.int32

### Integer dtype

`np.int32` is a **32-bit signed integer** — each element is stored in 32 bits (4 bytes), and values are whole numbers.

In [11]:
np.array([1, 2, 3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

**Result:** `array([1, 2, 3], dtype=int32)`

### Float dtype

`np.float32` is a **32-bit floating-point** number (decimal values).

In [12]:
np.array([1.1, 2.2, 3.3], dtype=np.float32)

array([1.1, 2.2, 3.3], dtype=float32)

**Result:** `array([1.1, 2.2, 3.3], dtype=float32)`

## 8. Type conversion

### Float to integer

Asking for an integer dtype with float input does not raise an error — the fractional part is **truncated (cut off), not rounded**.

In [13]:
np.array([1.1, 2.2, 3.3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

**Result:** `array([1, 2, 3], dtype=int32)` — `3.3` became `3`.

### Boolean to integer

`True` becomes `1` and `False` becomes `0`.

In [14]:
np.array([True, False, True], dtype=np.int32)

array([1, 0, 1], dtype=int32)

**Result:** `array([1, 0, 1], dtype=int32)`

## 9. Unicode / string arrays

In a dtype like `<U6`, `U` means a **Unicode string**, and the number is the **maximum number of characters** allocated per string. If I don't specify it, NumPy infers it from the longest string.

- `A` — inferred: `"Banana"` has 6 characters → `<U6`
- `B` — `U10` allows strings up to 10 characters
- `C` — `U5` allows only 5 characters, so `"Banana"` gets cut to `"Banan"`

In [15]:
A = np.array(["Apple", "Banana"])
B = np.array(["Apple", "Banana"], dtype="U10")
C = np.array(["Apple", "Banana"], dtype="U5")

print(A, A.dtype)
print(B, B.dtype)
print(C, C.dtype)

['Apple' 'Banana'] <U6
['Apple' 'Banana'] <U10
['Apple' 'Banan'] <U5


**Result:** `<U6`, `<U10`, and `<U5` with `Banana` → `Banan`. Strings that are too long are silently truncated, with no error.

## 10. Mixed integers and strings — dtype inference

An array has **one** dtype for all its elements. When I mix an integer with strings, NumPy looks for a common type that can hold everything — here that is a string type.

In [16]:
A = np.array([1, "4", 3])
print(A, A.dtype)

['1' '4' '3'] <U21


**Result:** all values were converted to strings (the numbers are now text, shown quoted).

### Explicit conversion: string numbers to integers

`"4"` is a valid numeric string, so when I explicitly request `dtype=np.int16` NumPy can convert it.

In [17]:
B = np.array([1, "4", 3], dtype=np.int16)
print(B, B.dtype)

[1 4 3] int16


**Result:** `[1 4 3] int16`

## 10b. ValueError experiment

Now with a string that is **not** a number. I asked for `int16`, so NumPy tried to convert every element:
- `1` and `3` convert fine
- `"a"` cannot be converted to an integer
- so NumPy raises a `ValueError`

I'm keeping the error output here on purpose — it is part of what I learned.

In [18]:
C = np.array([1, "a", 3], dtype=np.int16)

ValueError: invalid literal for int() with base 10: 'a'

**Result:** `ValueError: invalid literal for int() with base 10: 'a'`

## 11. `np.str_`

`np.str_` is NumPy's Unicode string scalar type. Passing `dtype=np.str_` explicitly requests string data.

In [19]:
A = np.array(["a", 4, "b"])
print(A, A.dtype)

B = np.array(["a", 3, "b"], dtype=np.str_)
print(B, B.dtype)

['a' '4' 'b'] <U21
['a' '3' 'b'] <U1


**Result:** both become string arrays — the number is converted to text, and the dtype is a `<U` string type.

## 12. NameError debugging

Here I used a variable `c` before defining it. Python looked for `c`, couldn't find it, and raised `NameError`.

In [20]:
C = np.array(["a", c, "b"], dtype=np.str_)

NameError: name 'c' is not defined

**Result:** `NameError: name 'c' is not defined` — a variable must be defined before it is used.

## 13. Python records

A list of tuples can act as simple records (one tuple per person: name, age, marks). Note that I wrote the age and marks as strings.

In [21]:
records = [
    ("Uday", "18", "88"),
    ("Yogesh", "19", "98")
]

print(records)
print("\n")
print(records[0])
print('\n')

data1 = np.array(records)
print(data1)

[('Uday', '18', '88'), ('Yogesh', '19', '98')]


('Uday', '18', '88')


[['Uday' '18' '88']
 ['Yogesh' '19' '98']]


**Result:** the records convert into a NumPy array. Because every value is a string, the whole array becomes a string array — no numeric types.

## 14. Structured arrays

A structured array lets **different fields have different dtypes** in one array. I give each field a name and a dtype:

| Field | dtype | Meaning |
|-------|-------|---------|
| `name` | `U15` | Unicode string, max 15 characters |
| `age` | `np.int32` | 32-bit integer |
| `marks` | `np.int32` | 32-bit integer |

Here the string `"18"` is converted to the integer `18` because the field dtype is `int32`.

In [22]:
data = np.array(
    records,
    dtype=[
        ("name", "U15"),
        ("age", np.int32),
        ("marks", np.int32)
    ]
)

print(data)
print(data[0])
print(data["name"])

[('Uday', 18, 88) ('Yogesh', 19, 98)]


('Uday', 18, 88)
['Uday' 'Yogesh']


**Result:**
```
[('Uday', 18, 88) ('Yogesh', 19, 98)]
('Uday', 18, 88)
['Uday' 'Yogesh']
```

- `data[0]` accesses the **first record**
- `data["name"]` accesses the **name field for all records**

## 15. Mixed-type arrays

With values of different types (int, float, bool, str), NumPy tries to find one common dtype. Because a string is present, everything is converted to strings.

In [23]:
het = np.array([5, 4.5, True, "a"])

print(het, het.dtype)

['5' '4.5' 'True' 'a'] <U32


**Result:** all elements became strings.

## 16. Object dtype

`dtype=object` lets the array hold **Python objects of different types** without forcing them into one primitive dtype. Each element keeps its own type.

In [24]:
het = np.array([5, 4.5, True, "a"], dtype=object)

print(het, het.dtype)
print(het[0], type(het[0]))

[5 4.5 True 'a'] object
5 <class 'int'>


**Result:** `[5 4.5 True 'a'] object` and `5 <class 'int'>` — the `int`, `float`, `bool` and `str` are all preserved as separate Python objects.

## Errors and Debugging Lessons

| Error | Message | Lesson |
|-------|---------|--------|
| `ValueError` | `invalid literal for int() with base 10: 'a'` | A string like `"a"` cannot be converted into an integer dtype. |
| `NameError` | `name 'c' is not defined` | A variable must be defined before it can be referenced. |

## Key Takeaways

- `np.array()` creates an array from a Python sequence; nesting adds dimensions.
- `.size` is the total number of elements; `.shape` is the size along each dimension (`(2, 2, 3)` → 12 elements).
- `.dtype` / `dtype=` control the data type: `np.int16`, `np.int32`, `np.float32`, `np.str_`.
- Float → int truncates; `True`/`False` → `1`/`0`.
- `<U6`, `<U10`, `<U5`: the number is the max string length — too-short limits cut strings.
- A normal array has one dtype; mixed values get a common dtype (often strings).
- Structured arrays give named fields with different dtypes; `dtype=object` keeps mixed Python types.
- `help()` is the quickest way to read documentation.

*Day 1 — basics only, a lot still to learn.*